default_audits = [
    'speed-index', 'first-contentful-paint',                         
    'largest-contentful-paint', 'max-potential-fid',                         
    'cumulative-layout-shift'
]

metrics_choices = [
    "all",
    "observedTotalCumulativeLayoutShift",
    "observedCumulativeLayoutShift",
    "observedLargestContentfulPaintAllFrames",
    "maxPotentialFID",
    "observedSpeedIndexTs",
    "observedFirstContentfulPaintTs",
    "observedTimeOrigin",
    "observedFirstPaint",
    "observedNavigationStartTs",
    "observedLargestContentfulPaintAllFramesTs",
    "speedIndex",
    "observedFirstContentfulPaint",
    "observedLastVisualChangeTs",
    "cumulativeLayoutShiftMainFrame",
    "observedLastVisualChange",
    "cumulativeLayoutShift",
    "largestContentfulPaint",
    "observedDomContentLoaded",
    "firstContentfulPaint",
    "observedCumulativeLayoutShiftMainFrame",
    "observedFirstVisualChange",
    "observedFirstPaintTs",
    "totalCumulativeLayoutShift",
    "observedFirstMeaningfulPaint",
    "interactive",
    "observedTraceEnd",
    "observedFirstMeaningfulPaintTs",
    "totalBlockingTime",
    "observedFirstContentfulPaintAllFramesTs",
    "observedLargestContentfulPaint",
    "observedNavigationStart",
    "observedLoad",
    "observedFirstVisualChangeTs",
    "observedFirstContentfulPaintAllFrames",
    "observedTimeOriginTs",
    "observedTraceEndTs",
    "observedLoadTs",
    "observedDomContentLoadedTs",
    "observedSpeedIndex",
    "firstMeaningfulPaint",
    "observedLargestContentfulPaintTs"
]